// src/routes/login/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { authClient } from '$lib/auth-client'
  import Card from '$lib/components/ui/Card.svelte'
  import InlineAlert from '$lib/components/ui/InlineAlert.svelte'
  import TextField from '$lib/components/ui/TextField.svelte'

  let email = $state('')
  let password = $state('')
  let busy = $state(false)
  let message = $state('')

  async function submit() {
    busy = true
    message = ''
    try {
      const result = await authClient.signIn.email({ email, password })
      if (result.error || !result.data)
        message = 'Email atau password tidak valid'
      else await goto('/dashboard')
    } catch {
      message = 'Email atau password tidak valid'
    } finally {
      busy = false
    }
  }
</script>

<svelte:head><title>Login admin — LEPS</title></svelte:head>
<main class="login-frame">
  <Card class="login-card">
    <p class="eyebrow">ADMIN CONTROL ROOM</p>
    <h1>Selamat datang kembali.</h1>
    <p class="login-copy">
      Masuk untuk mengelola license dan memantau aktivitas verifikasi.
    </p>
    {#if message}<InlineAlert>{message}</InlineAlert>{/if}
    <form
      onsubmit={(event) => {
        event.preventDefault()
        submit()
      }}
    >
      <TextField
        id="email"
        label="Email"
        type="email"
        bind:value={email}
        required
        autocomplete="email"
      />
      <TextField
        id="password"
        label="Password"
        type="password"
        bind:value={password}
        required
        autocomplete="current-password"
      />
      <button type="submit" disabled={busy}
        >{busy ? 'Memeriksa…' : 'Masuk →'}</button
      >
    </form>
    <small>Protected admin access · Session managed by Better Auth</small>
  </Card>
</main>

<style>
  .login-frame {
    min-height: 100vh;
    display: grid;
    place-items: center;
    padding: 1rem;
    background: linear-gradient(135deg, var(--sand) 0 40%, var(--paper) 40%);
  }
  :global(.login-card) {
    width: min(100%, 440px);
    display: grid;
    gap: 1rem;
  }
  .eyebrow {
    margin: 0;
    color: var(--red);
    font-size: 0.78rem;
    font-weight: 900;
    letter-spacing: 0.09em;
  }
  h1,
  p {
    margin: 0;
  }
  h1 {
    font-size: clamp(2rem, 5vw, 2.7rem);
    line-height: 0.95;
    letter-spacing: -0.05em;
  }
  .login-copy {
    line-height: 1.5;
  }
  form {
    display: grid;
    gap: 1rem;
    margin-top: 0.35rem;
  }
  button {
    min-height: 44px;
    border: var(--border);
    border-radius: 8px;
    background: var(--red);
    box-shadow: var(--shadow-sm);
    color: var(--white);
    font-weight: 900;
    text-transform: uppercase;
    cursor: pointer;
  }
  :global(.login-card) small {
    border-top: 1px solid var(--ink);
    padding-top: 1rem;
    font-size: 0.72rem;
    font-weight: 700;
  }
  @media (max-width: 600px) {
    .login-frame {
      background: var(--paper);
    }
  }
</style>

// app/login/page.tsx
"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { signIn, useSession } from "@/lib/auth-client";

export default function LoginPage() {
  const router = useRouter();
  const { data: session } = useSession();
  const [showPassword, setShowPassword] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = React.useState(false);

  React.useEffect(() => {
    if (session?.user) {
      router.replace("/dashboard");
    }
  }, [router, session?.user]);

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError(null);
    setIsSubmitting(true);

    const formData = new FormData(event.currentTarget);
    const result = await signIn.email({
      email: String(formData.get("email") ?? ""),
      password: String(formData.get("password") ?? ""),
    });

    setIsSubmitting(false);

    if (result.error) {
      setError(result.error.message ?? "Unable to sign in.");
      return;
    }

    router.push("/dashboard");
    router.refresh();
  }

  return (
    <main className="grid min-h-screen place-items-center bg-background px-4 py-10">
      <div className="w-full max-w-md">
        <div className="mb-6 flex items-center justify-center gap-3">
          <div className="flex h-11 w-11 items-center justify-center rounded-md border border-emerald-400/30 bg-emerald-400/10 text-emerald-300">
            <ShieldCheck className="h-6 w-6" />
          </div>
          <div>
            <div className="text-lg font-semibold tracking-normal">LEPS</div>
            <div className="text-sm text-muted-foreground">Super Admin</div>
          </div>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Sign in</CardTitle>
            <CardDescription>
              Protected access for the single-tenant admin workspace.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-5">
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <div className="relative">
                  <Mail className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input
                    id="email"
                    name="email"
                    type="email"
                    placeholder="admin@leps.local"
                    autoComplete="email"
                    className="pl-9"
                    required
                  />
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <div className="relative">
                  <LockKeyhole className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input
                    id="password"
                    name="password"
                    type={showPassword ? "text" : "password"}
                    placeholder="Password"
                    autoComplete="current-password"
                    className="pl-9 pr-11"
                    required
                  />
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="absolute right-0 top-0 h-10 w-10"
                    aria-label={showPassword ? "Hide password" : "Show password"}
                    onClick={() => setShowPassword((value) => !value)}
                  >
                    {showPassword ? (
                      <EyeOff className="h-4 w-4" />
                    ) : (
                      <Eye className="h-4 w-4" />
                    )}
                  </Button>
                </div>
              </div>
              {error ? (
                <div className="rounded-md border border-rose-500/25 bg-rose-500/10 px-3 py-2 text-sm text-rose-200">
                  {error}
                </div>
              ) : null}
              <Button type="submit" className="w-full" disabled={isSubmitting}>
                {isSubmitting ? "Signing in..." : "Sign in"}
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
